// <auto-generated />
using System;
using Ecomtik.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ecomtik.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ecomtik.Models.Computation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("FunctionExpr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LowerBound")
                        .HasColumnType("numeric");

                    b.Property<int>("MethodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Result")
                        .HasColumnType("numeric");

                    b.Property<int>("Steps")
                        .HasColumnType("integer");

                    b.Property<decimal>("UpperBound")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MethodId");

                    b.ToTable("Computations");
                });

            modelBuilder.Entity("Ecomtik.Models.Method", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Methods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "simpson",
                            Name = "Метод Симпсона"
                        },
                        new
                        {
                            Id = 2,
                            Code = "trapezoidal",
                            Name = "Метод трапеций"
                        },
                        new
                        {
                            Id = 3,
                            Code = "monte_carlo",
                            Name = "Метод Монте-Карло"
                        });
                });

            modelBuilder.Entity("Ecomtik.Models.Computation", b =>
                {
                    b.HasOne("Ecomtik.Models.Method", "Method")
                        .WithMany()
                        .HasForeignKey("MethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Method");
                });
#pragma warning restore 612, 618
        }
    }
}
